Repository depromeet/moodpic-web, pull requests merged in 2022-05, with the labels that each got.

#77 feat: folder button 추가 (#21)
  components/Common/Tag/FolderButton.stories.tsx
  components/Common/Tag/FolderButton.tsx
  public/svgs/folder.svg
  styles/mixins.ts
Labels: Type: Style :nail_care:

#74 Common component re-export 리팩토링
  components/Common/AppLayout/AppLayout.tsx
  components/Common/index.tsx
  components/Example/BottomSheetExample.tsx
  components/Example/ModalExample.tsx
  components/Home/Banner/Banner.tsx
  pages/_app.tsx
  pages/index.tsx
Labels: Type: Enhancement 📈

#82 button large size 에 disabled style 추가
  components/Common/Button/Button.styles.ts
Labels: Type: Style :nail_care:

#75 [WIP] 글 작성 페이지 ( 1차 감정 선택, 질문 작성, 2차 감정 선택, 완료 )
  components/Common/AppLayout/AppLayout.styles.ts
  components/Common/Progress/Progress.tsx
  components/Common/SelectButton/SelectButton.tsx
  components/Common/TextArea/TextArea.styles.ts
  components/Common/TextField/TextField.styles.ts
  components/Common/TextField/TextField.tsx
  components/Common/Toggle/Toggle.styles.ts
  components/Common/WritingButton/WritingButton.styles.ts
  components/Common/index.tsx
  components/Complete/Complete.tsx
  components/CurrentEmotion/CurrentEmotion.tsx
  components/Home/Banner/Banner.tsx
  components/PreEmotion/PreEmotion.tsx
  components/Question/Question.styles.ts
  components/Question/Question.tsx
  hooks/useDialog.ts
  hooks/useNextProgressStep.ts
  hooks/useTypeInput.ts
  pages/index.tsx
  pages/posts/index.tsx
  pages/write/complete.tsx
  pages/write/current-emotion.tsx
  pages/write/index.tsx
  pages/write/pre-emotion.tsx
  pages/write/question.tsx
  public/svgs/bgclose.svg
  store/progressStep/atom.ts
  store/tooltip/atom.ts
  styles/theme.ts
Labels: Type: Feature Request :raised_hands:

#96 feat: 태그 추가 삭제 컴포넌트 (를 곁들인 감정 등록 flow 전부)
  components/BottomSheetFolderList/BottomSheetFolderList.tsx
  components/Common/SelectButton/FirstCategorySelect.tsx
  components/Common/SelectButton/SecondCategorySelect.skeleton.tsx
  components/Common/SelectButton/SecondCategorySelect.tsx
  components/Common/SelectButton/SelectButton.tsx
  components/Common/TagButton/TagButton.styles.ts
  components/Common/TagButton/TagButton.tsx
  components/Common/TextArea/TextArea.tsx
  components/Common/TextField/TextField.styles.ts
  components/Common/TextField/TextField.tsx
  components/Complete/Complete.tsx
  components/CurrentEmotion/CurrentEmotion.styles.ts
  components/CurrentEmotion/CurrentEmotion.tsx
  components/Dialog/DialogFolderForm.tsx
  components/Example/BottomSheetExample.tsx
  components/Post/PostDetail.style.ts
  components/PreEmotion/PreEmotion.tsx
  components/Question/Question.tsx
  hooks/apis/folder/useFolderMutation.ts
  hooks/apis/post/useCategoryListQuery.ts
  hooks/apis/post/useFirstCategoryQuery.ts
  hooks/apis/post/usePostMutation.ts
  hooks/useTypeInput.ts
  pages/_app.tsx
  pages/write/index.tsx
  public/images/complete.png
  public/svgs/CheckCirclePr.svg
  service/apis/postService.ts
  shared/api/apiClient.ts
  shared/constants/queryKey.ts
  shared/type/postResponse.ts
  store/postResponse/atom.ts
  store/questionMode/atom.ts
Labels: Type: Feature Request :raised_hands:

#136 kakao redirect url location -> window.location.origin 으로 변경
  pages/oauth/index.tsx
  shared/constants/auth.ts
  shared/constants/routes.ts
Labels: Type: Bug 🐛
