Repository depromeet/moodpic-web, pull requests merged in 2022-06, with the labels that each got.

#135 useIsMounted hooks 로직 변경
  hooks/useIsMounted.ts
  pages/index.tsx
Labels: Type: Bug 🐛

#119 refactor: post
  components/BottomSheetFolderList/BottomSheetFolderList.tsx
  components/Common/AppLayout/AppLayout.styles.ts
  components/Common/AppLayout/AppLayout.tsx
  components/Common/SelectButton/FirstCategorySelect.tsx
  components/Common/SelectButton/SecondCategorySelect.tsx
  components/Complete/Complete.tsx
  components/CurrentEmotion/CurrentEmotion.tsx
  components/Figure/ANXIOUS.tsx
  components/Figure/CALMDOWN.tsx
  components/Figure/DISAPPOINTMENT.tsx
  components/Figure/DONTKNOW.tsx
  components/Figure/EASYGOING.tsx
  components/Figure/Figure.styles.ts
  components/Figure/IRRITATION.tsx
  components/Figure/JOY.tsx
  components/Figure/LETHARGY.tsx
  components/Figure/PROUD.tsx
  components/Figure/REGRET.tsx
  components/Figure/RELIEF.tsx
  components/Figure/SADNESS.tsx
  components/PreEmotion/PreEmotion.tsx
  components/Question/Question.styles.ts
  components/Question/Question.tsx
  hooks/apis/post/usePostMutation.ts
  hooks/post/usePostEditForm.ts
  hooks/useBottomSheet.ts
  pages/_app.tsx
  pages/_document.tsx
  pages/write/index.tsx
  public/images/complete.png
  public/images/img_ANXIOUS.png
  public/images/img_CALMDOWN.png
  public/images/img_DISAPPOINTMENT.png
  public/images/img_DONTKNOW.png
  public/images/img_EASYGOING.png
  public/images/img_IRRITATION.png
  public/images/img_JOY.png
  public/images/img_LETHARGY.png
  public/images/img_PROUD.png
  public/images/img_REGRET.png
  public/images/img_RELIEF.png
  public/images/img_SADNESS.png
  service/apis/postService.ts
  shared/type/figure.ts
  shared/type/post.ts
  shared/type/postResponse.ts
  shared/utils/fetcher.ts
  store/post/atom.ts
  store/postResponse/atom.ts
  styles/globals.css
Labels: Type: Enhancement 📈

#150 공유하기 기능
  .idea/workspace.xml
  components/Dialog/DialogWarning.tsx
  components/Home/Header/Header.tsx
  components/Share/CategoryBox/CategoryBox.tsx
  components/Share/CategoryOptionItem/CategoryOptionItem.tsx
  hooks/apis/index.ts
  hooks/apis/member/index.ts
  hooks/apis/member/useMemberQuery.ts
  hooks/apis/post/index.ts
  hooks/apis/post/usePostsQuery.ts
  hooks/apis/post/useSharedPostQuery.ts
  package-lock.json
  pages/posts/[postId].tsx
  pages/share/index.tsx
  pages/share/post/[ldm].tsx
  public/svgs/check.svg
  public/svgs/disappointedFace.svg
  public/svgs/empathizeFace.svg
  public/svgs/letter.svg
  public/svgs/reconcile.svg
  public/svgs/sorryFace.svg
  public/svgs/thanks.svg
  public/svgs/tiredFace.svg
  public/svgs/union.svg
  service/apis/memberService.ts
  service/apis/shareService.ts
  shared/constants/category.ts
  shared/constants/queryKey.ts
  shared/constants/share.ts
  shared/constants/url.ts
  shared/type/member.ts
  shared/type/share.ts
  shared/utils/copyClipboard.ts
  shared/utils/fetcher.ts
  shared/utils/getBaseUrl.ts
Labels: Type: Feature Request :raised_hands:

#149 feat: 마이페이지
  components/BottomSheetFolderList/BottomSheetFolderList.styles.ts
  components/BottomSheetFolderList/BottomSheetFolderList.tsx
  components/Common/BottomSheetContainer/BottomSheetContainer.styles.ts
  components/Common/Button/Button.styles.ts
  components/Common/Dialog/Dialog.styles.ts
  components/Common/Dialog/Dialog.tsx
  components/Common/DropdownMenu/DropdownMenu.tsx
  components/Common/IconButton/IconButton.tsx
  components/Common/Progress/Progress.tsx
  components/Common/ReadyForOpen/ReadyForOpen.tsx
  components/Common/SelectButton/FirstCategorySelect.tsx
  components/Common/SelectButton/SecondCategorySelect.tsx
  components/Common/TagButton/TagButton.styles.ts
  components/Common/Toggle/Toggle.styles.ts
  components/Common/WritingButton/WritingButton.styles.ts
  components/Complete/Complete.tsx
  components/CurrentEmotion/CurrentEmotion.styles.ts
  components/CurrentEmotion/CurrentEmotion.tsx
  components/Dialog/DialogWarning.tsx
  components/Home/CollectedFolder/CollectedFolder.styles.ts
  components/Home/TabHeader/TabHeader.tsx
  components/Home/Tabs/Tabs.tsx
  components/MypageContentList/MypageContentList.tsx
  components/MypageHeader/MypageHeader.tsx
  components/PreEmotion/PreEmotion.tsx
  components/Question/Question.styles.ts
  components/Question/Question.tsx
  components/Share/CategoryBox/CategoryBox.tsx
  components/TagSearch/PopularTagItem/PopularTagItem.tsx
  next.config.js
  pages/_app.tsx
  pages/_document.tsx
  pages/mypage/index.tsx
  pages/mypage/notice.tsx
  pages/mypage/posts.tsx
  pages/mypage/withdraw.tsx
  pages/search/index.tsx
  pages/share/index.tsx
  pages/write/index.tsx
  public/images/person-running.png
  public/svgs/right.svg
  shared/constants/routes.ts
Labels: Type: Feature Request :raised_hands:

#172 date format 함수 Safari 버그 수정
  shared/utils/date.ts
Labels: Type: Bug 🐛

#188 style: 텍스트 중앙 맞추기
  components/Common/ReadyForOpen/ReadyForOpen.tsx
Labels: low, Type: Style :nail_care:

#194 hotfix: baseurl 변경
  shared/constants/url.ts
Labels: high, Type: Bug 🐛

#193 style: PostItem 컴포넌트 스타일 수정 (#192)
  components/Post/PostItem/PostItem.tsx
  pages/search/result/index.tsx
Labels: Type: Style :nail_care:

#204 feat: pwa 적용중
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/_middleware.ts
  public/favicon.png
  public/icon-192x192.png
  public/icon-256x256.png
  public/icon-384x384.png
  public/icon-512x512.png
  public/manifest.json
  public/sw.js
  public/sw.js.map
  public/workbox-74d02f44.js
  public/workbox-74d02f44.js.map
Labels: Type: Feature Request :raised_hands:

#236 docs: README.md 업데이트
  README.md
Labels: documentation

#239 PWA 보완
  next.config.js
  pages/_app.tsx
  pages/_document.tsx
Labels: Type: Enhancement 📈, Type: Feature Request :raised_hands:

#242 Fix: rollback 된 코드 복원
  README.md
  components/Common/Toast/Toast.tsx
  components/Home/CollectedFolder/CollectedFolder.styles.ts
  components/Home/FloatingButton/FloatingButton.tsx
  components/Post/PostList/PostList.style.ts
  components/Post/PostList/PostList.tsx
  components/Post/WritingButton.tsx
  hooks/apis/folder/useFolderMutation.ts
  lib/gtag.js
  pages/_app.tsx
  pages/_document.tsx
  pages/login/index.tsx
  pages/oauth/callback/kakao/index.tsx
  pages/posts/[postId]/edit.tsx
  pages/posts/dontknow-feelings.tsx
  pages/posts/index.tsx
  pages/share/post/[ldm].tsx
  public/robots.txt
  public/sitemap.xml
  service/apis/folderService.ts
  shared/constants/queryKey.ts
Labels: Type: Bug 🐛
