Repository depromeet/moodpic-web, pull requests merged in 2022-08, with the labels that each got.

#266 닉네임 변경
  components/Dialog/DialogFolderForm.tsx
  components/MypageHeader/MypageHeader.tsx
  hooks/apis/member/useMemberMutation.ts
  service/apis/memberService.ts
  shared/constants/queryKey.ts
Labels: Type: Feature Request :raised_hands:

#254 feat: apple-touch-startup-image 추가
  pages/_document.tsx
  public/images/splash.png
Labels: Type: Feature Request :raised_hands:

#269 refactor: next/router => next/link 로 리팩토링
  components/Home/Banner/Banner.tsx
Labels: Type: Enhancement 📈

#267 fix: Textarea 컴포넌트 padding 유지를 위해 wrapper 추가
  components/Common/TextArea/TextArea.styles.ts
  components/Common/TextArea/TextArea.tsx
Labels: Type: Style :nail_care:

#265 refactor: next/script 사용하는 방식으로 변경
  pages/_app.tsx
  pages/_document.tsx
Labels: Type: Enhancement 📈
