Repository depromeet/moodpic-web, pull requests merged in 2022-04, with the labels that each got.

#5 MyApp 반환되는 JSX 내 괄호 제거
  pages/_app.tsx
Labels: Type: Bug 🐛

#20 테스트 관련 설정 및 가이드라인 코드 작성
  components/Common/StoryExample/StoryExample.test.tsx
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  public/mockServiceWorker.js
Labels: env

#40 Pages 기본 구조 추가
  pages/mypage/withdraw.tsx
  pages/posts/[postId].tsx
  pages/posts/letters/[letterId].tsx
  pages/posts/letters/write.tsx
  pages/search/index.tsx
  pages/write/complete.tsx
  pages/write/current-emotion.tsx
  pages/write/pre-emotion.tsx
  pages/write/question.tsx
Labels: Type: Feature Request :raised_hands:

#33 Github Action을 이용한 테스트 자동화
  .github/workflows/front-test.yml
Labels: Type: Enhancement 📈

#41 공용 컴포넌트 - Card component 추가
  components/Card/Card.stories.tsx
  components/Card/Card.styles.ts
  components/Card/Card.tsx
Labels: Type: Feature Request :raised_hands:

#44 Toggle, WritingButton 스토리북에 추가 (#36)
  components/Common/Toggle/Toggle.stories.tsx
  components/Common/WritingButton/WritingButton.stories.tsx
  components/Common/WritingButton/WritingButton.tsx
Labels: Type: Enhancement 📈

#51 Toast
  components/Common/AppLayout/AppLayout.tsx
  components/Common/Toast/Toast.styles.ts
  components/Common/Toast/Toast.tsx
  components/Common/index.tsx
  components/Example/BottomSheetExample.tsx
  components/Example/Example.styles.ts
  components/Example/Example.tsx
  components/Example/ToastExample.tsx
  components/Home/Tabs.tsx
  hooks/useToast.ts
  package-lock.json
  package.json
  pages/index.tsx
  shared/type/global.d.ts
Labels: medium, Type: Feature Request :raised_hands:
